package news

import "time"

// DrResponse is autogenerated based on the JSON response from dr using the tool https://transform.tools/json-to-go
type DrResponse struct {
	Data struct {
		FrontPage struct {
			TopStories []struct {
				URL     string      `json:"url"`
				Title   string      `json:"title"`
				Live    bool        `json:"live"`
				Channel interface{} `json:"channel"`
				Image   struct {
					URL    string `json:"url"`
					Width  int    `json:"width"`
					Height int    `json:"height"`
				} `json:"image"`
				Article struct {
					Type         string `json:"type"`
					Urn          string `json:"urn"`
					URL          string `json:"url"`
					Title        string `json:"title"`
					Format       string `json:"format"`
					Publications []struct {
						Breaking       bool `json:"breaking"`
						Live           bool `json:"live"`
						ServiceChannel struct {
							Urn string `json:"urn"`
						} `json:"serviceChannel"`
					} `json:"publications"`
					Summary     string    `json:"summary"`
					StartDate   time.Time `json:"startDate"`
					TeaserImage struct {
						Default struct {
							URL string `json:"url"`
						} `json:"default"`
					} `json:"teaserImage"`
					TeaserVideo interface{} `json:"teaserVideo"`
					Head        []struct {
						Type string `json:"type"`
					} `json:"head"`
					Contributions []struct {
						Agent struct {
							Name string `json:"name"`
						} `json:"agent"`
					} `json:"contributions"`
					Site struct {
						URL          string `json:"url"`
						Urn          string `json:"urn"`
						Title        string `json:"title"`
						Presentation struct {
							Colors struct {
								Primary struct {
									Brand struct {
										Solid string `json:"solid"`
										Text  string `json:"text"`
									} `json:"brand"`
									Interaction struct {
										Solid string `json:"solid"`
										Text  string `json:"text"`
									} `json:"interaction"`
								} `json:"primary"`
								Secondary struct {
									Brand struct {
										Solid string `json:"solid"`
										Text  string `json:"text"`
									} `json:"brand"`
									Interaction struct {
										Solid string `json:"solid"`
										Text  string `json:"text"`
									} `json:"interaction"`
								} `json:"secondary"`
							} `json:"colors"`
						} `json:"presentation"`
					} `json:"site"`
				} `json:"article"`
			} `json:"topStories"`
		} `json:"frontPage"`
	} `json:"data"`
	Extensions struct {
		DeprecatedUsages []string `json:"deprecatedUsages"`
	} `json:"extensions"`
}
